# Use an official node runtime as a parent image
FROM node:20

WORKDIR /app/frontend

#Install dependencies
COPY package.json yarn.lock* /app/frontend/

RUN npm install

# Add rest of the client code
COPY . .

# Change directory to the React app directory
WORKDIR /app/frontend/jkr_records

#Build the React App for production
RUN npm run build 


EXPOSE 3001

CMD npm start

