# Generated by Django 3.2.2 on 2024-04-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('foto', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('foto', models.URLField()),
                ('spotify', models.URLField(blank=True, null=True)),
                ('applemusic', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('foto', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('feat', models.CharField(blank=True, max_length=200)),
                ('producer', models.CharField(max_length=200)),
                ('foto', models.URLField(blank=True, null=True)),
                ('link_spotify', models.URLField(blank=True, null=True)),
                ('link_youtube', models.URLField(blank=True, null=True)),
                ('link_applemusic', models.URLField(blank=True, null=True)),
                ('reproducciones_spotify', models.PositiveIntegerField(default=0)),
                ('reproducciones_youtube', models.PositiveIntegerField(default=0)),
                ('reproducciones_applemusic', models.PositiveIntegerField(default=0)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artists')),
            ],
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=200)),
                ('feat', models.CharField(blank=True, max_length=200)),
                ('foto', models.URLField(blank=True, null=True)),
                ('preview', models.URLField(blank=True, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artists')),
            ],
        ),
    ]
