# Generated by Django 3.2.2 on 2024-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='jkrpoints',
            field=models.IntegerField(default=0, verbose_name='JKR Points'),
        ),
    ]
